services:
  app:
    container_name: topic_hives_app
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000
    environment:
      - DB_TYPE=postgres
      - DB_HOST=th_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_NAME=topic_hives
    depends_on:
      - th_db
  th_db:
    container_name: th_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=topic_hives
    volumes:
      - pgdata:/var/lib/posgresql/data
volumes:
  pgdata: {}